# Generated by Django 3.2.9 on 2021-11-22 09:14

from django.db import migrations, models
import django.db.models.deletion
import enum


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name=enum.auto)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.CharField(blank=True, default='email@email.com', max_length=100)),
                ('phone', models.CharField(blank=True, default='021123456789', max_length=100)),
                ('notes', models.CharField(blank=True, default='empty', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name=enum.auto)),
                ('name', models.CharField(blank=True, default='teman-kantor', max_length=100)),
                ('slug', models.CharField(blank=True, default='abcde', max_length=100)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ContactLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.contact')),
                ('label_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.label')),
            ],
            options={
                'ordering': ['contact_id'],
            },
        ),
    ]
